// Calling codes for the /contact phone field. Kept as a local list
// rather than a dependency: the form only needs code + label, and a
// curated list keeps the bundle small and the dropdown searchable.
// Ordered by name; the select is searchable so length is fine.

export interface CallingCode {
  /** ISO 3166-1 alpha-2 */
  code: string
  name: string
  /** E.164 calling code with plus sign, e.g. '+49' */
  callingCode: string
}

export const CALLING_CODES: CallingCode[] = [
  { code: 'af', name: 'Afghanistan', callingCode: '+93' },
  { code: 'al', name: 'Albania', callingCode: '+355' },
  { code: 'dz', name: 'Algeria', callingCode: '+213' },
  { code: 'ar', name: 'Argentina', callingCode: '+54' },
  { code: 'am', name: 'Armenia', callingCode: '+374' },
  { code: 'au', name: 'Australia', callingCode: '+61' },
  { code: 'at', name: 'Austria', callingCode: '+43' },
  { code: 'az', name: 'Azerbaijan', callingCode: '+994' },
  { code: 'bh', name: 'Bahrain', callingCode: '+973' },
  { code: 'bd', name: 'Bangladesh', callingCode: '+880' },
  { code: 'by', name: 'Belarus', callingCode: '+375' },
  { code: 'be', name: 'Belgium', callingCode: '+32' },
  { code: 'bo', name: 'Bolivia', callingCode: '+591' },
  { code: 'ba', name: 'Bosnia and Herzegovina', callingCode: '+387' },
  { code: 'br', name: 'Brazil', callingCode: '+55' },
  { code: 'bg', name: 'Bulgaria', callingCode: '+359' },
  { code: 'kh', name: 'Cambodia', callingCode: '+855' },
  { code: 'cm', name: 'Cameroon', callingCode: '+237' },
  { code: 'ca', name: 'Canada', callingCode: '+1' },
  { code: 'cl', name: 'Chile', callingCode: '+56' },
  { code: 'cn', name: 'China', callingCode: '+86' },
  { code: 'co', name: 'Colombia', callingCode: '+57' },
  { code: 'cr', name: 'Costa Rica', callingCode: '+506' },
  { code: 'hr', name: 'Croatia', callingCode: '+385' },
  { code: 'cy', name: 'Cyprus', callingCode: '+357' },
  { code: 'cz', name: 'Czechia', callingCode: '+420' },
  { code: 'dk', name: 'Denmark', callingCode: '+45' },
  { code: 'do', name: 'Dominican Republic', callingCode: '+1' },
  { code: 'ec', name: 'Ecuador', callingCode: '+593' },
  { code: 'eg', name: 'Egypt', callingCode: '+20' },
  { code: 'sv', name: 'El Salvador', callingCode: '+503' },
  { code: 'ee', name: 'Estonia', callingCode: '+372' },
  { code: 'et', name: 'Ethiopia', callingCode: '+251' },
  { code: 'fi', name: 'Finland', callingCode: '+358' },
  { code: 'fr', name: 'France', callingCode: '+33' },
  { code: 'ge', name: 'Georgia', callingCode: '+995' },
  { code: 'de', name: 'Germany', callingCode: '+49' },
  { code: 'gh', name: 'Ghana', callingCode: '+233' },
  { code: 'gr', name: 'Greece', callingCode: '+30' },
  { code: 'gt', name: 'Guatemala', callingCode: '+502' },
  { code: 'hk', name: 'Hong Kong', callingCode: '+852' },
  { code: 'hu', name: 'Hungary', callingCode: '+36' },
  { code: 'is', name: 'Iceland', callingCode: '+354' },
  { code: 'in', name: 'India', callingCode: '+91' },
  { code: 'id', name: 'Indonesia', callingCode: '+62' },
  { code: 'ir', name: 'Iran', callingCode: '+98' },
  { code: 'iq', name: 'Iraq', callingCode: '+964' },
  { code: 'ie', name: 'Ireland', callingCode: '+353' },
  { code: 'il', name: 'Israel', callingCode: '+972' },
  { code: 'it', name: 'Italy', callingCode: '+39' },
  { code: 'jm', name: 'Jamaica', callingCode: '+1' },
  { code: 'jp', name: 'Japan', callingCode: '+81' },
  { code: 'jo', name: 'Jordan', callingCode: '+962' },
  { code: 'kz', name: 'Kazakhstan', callingCode: '+7' },
  { code: 'ke', name: 'Kenya', callingCode: '+254' },
  { code: 'kw', name: 'Kuwait', callingCode: '+965' },
  { code: 'lv', name: 'Latvia', callingCode: '+371' },
  { code: 'lb', name: 'Lebanon', callingCode: '+961' },
  { code: 'ly', name: 'Libya', callingCode: '+218' },
  { code: 'lt', name: 'Lithuania', callingCode: '+370' },
  { code: 'lu', name: 'Luxembourg', callingCode: '+352' },
  { code: 'my', name: 'Malaysia', callingCode: '+60' },
  { code: 'mt', name: 'Malta', callingCode: '+356' },
  { code: 'mx', name: 'Mexico', callingCode: '+52' },
  { code: 'md', name: 'Moldova', callingCode: '+373' },
  { code: 'me', name: 'Montenegro', callingCode: '+382' },
  { code: 'ma', name: 'Morocco', callingCode: '+212' },
  { code: 'np', name: 'Nepal', callingCode: '+977' },
  { code: 'nl', name: 'Netherlands', callingCode: '+31' },
  { code: 'nz', name: 'New Zealand', callingCode: '+64' },
  { code: 'ng', name: 'Nigeria', callingCode: '+234' },
  { code: 'mk', name: 'North Macedonia', callingCode: '+389' },
  { code: 'no', name: 'Norway', callingCode: '+47' },
  { code: 'om', name: 'Oman', callingCode: '+968' },
  { code: 'pk', name: 'Pakistan', callingCode: '+92' },
  { code: 'pa', name: 'Panama', callingCode: '+507' },
  { code: 'py', name: 'Paraguay', callingCode: '+595' },
  { code: 'pe', name: 'Peru', callingCode: '+51' },
  { code: 'ph', name: 'Philippines', callingCode: '+63' },
  { code: 'pl', name: 'Poland', callingCode: '+48' },
  { code: 'pt', name: 'Portugal', callingCode: '+351' },
  { code: 'qa', name: 'Qatar', callingCode: '+974' },
  { code: 'ro', name: 'Romania', callingCode: '+40' },
  { code: 'ru', name: 'Russia', callingCode: '+7' },
  { code: 'sa', name: 'Saudi Arabia', callingCode: '+966' },
  { code: 'rs', name: 'Serbia', callingCode: '+381' },
  { code: 'sg', name: 'Singapore', callingCode: '+65' },
  { code: 'sk', name: 'Slovakia', callingCode: '+421' },
  { code: 'si', name: 'Slovenia', callingCode: '+386' },
  { code: 'za', name: 'South Africa', callingCode: '+27' },
  { code: 'kr', name: 'South Korea', callingCode: '+82' },
  { code: 'es', name: 'Spain', callingCode: '+34' },
  { code: 'lk', name: 'Sri Lanka', callingCode: '+94' },
  { code: 'se', name: 'Sweden', callingCode: '+46' },
  { code: 'ch', name: 'Switzerland', callingCode: '+41' },
  { code: 'tw', name: 'Taiwan', callingCode: '+886' },
  { code: 'tz', name: 'Tanzania', callingCode: '+255' },
  { code: 'th', name: 'Thailand', callingCode: '+66' },
  { code: 'tn', name: 'Tunisia', callingCode: '+216' },
  { code: 'tr', name: 'Turkey', callingCode: '+90' },
  { code: 'ua', name: 'Ukraine', callingCode: '+380' },
  { code: 'ae', name: 'United Arab Emirates', callingCode: '+971' },
  { code: 'gb', name: 'United Kingdom', callingCode: '+44' },
  { code: 'us', name: 'United States', callingCode: '+1' },
  { code: 'uy', name: 'Uruguay', callingCode: '+598' },
  { code: 'uz', name: 'Uzbekistan', callingCode: '+998' },
  { code: 've', name: 'Venezuela', callingCode: '+58' },
  { code: 'vn', name: 'Vietnam', callingCode: '+84' },
]
